services:

  airflow:
    image: airflow-dev
    build: .
    container_name: airflow
    ports:
      - 8080:8080
    volumes:
      - ../dags/:/opt/airflow/dags
      - ../scripts/:/opt/app/scripts/
      - ../data:/data
